/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pss.view;

import com.pss.dao.ClientDao;
import com.pss.dao.ClientImpl;
import com.pss.dao.ProductImpl;
import com.pss.po.Client;
import com.pss.util.LocationUtil;
import com.pss.util.StringUtile;
import com.pss.util.UUIDUtils;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class CustomerManagement extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame2
     */
    public CustomerManagement() {
        initComponents();
        LocationUtil.setFullScreen(this);  //设置全屏显示
         this.btnUpdate.setEnabled(false);
        this.btnDel.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtss = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClient = new javax.swing.JTable();
        tblName = new javax.swing.JLabel();
        tblTel = new javax.swing.JLabel();
        tblAddress = new javax.swing.JLabel();
        tblPost = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPost = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("客户管理");

        txtss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtssActionPerformed(evt);
            }
        });

        tblClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "客户姓名", "电话", "送货地址", "邮编"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClient);

        tblName.setText("客户姓名");

        tblTel.setText("电话");

        tblAddress.setText("送货地址");

        tblPost.setText("邮编");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        btnAdd.setText("增加");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDel.setText("删除");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnUpdate.setText("更新");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSearch.setText("查询");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnQuit.setText("取消");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(btnAdd)
                                .addGap(27, 27, 27)
                                .addComponent(btnDel)
                                .addGap(42, 42, 42)
                                .addComponent(btnUpdate)
                                .addGap(161, 161, 161)
                                .addComponent(btnQuit))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(223, 223, 223)
                                        .addComponent(txtss, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(btnSearch))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tblName)
                                            .addComponent(tblTel))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(131, 131, 131)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tblPost, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tblAddress))))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAddress)
                                    .addComponent(txtPost, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblName)
                    .addComponent(tblAddress)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblTel)
                    .addComponent(tblPost)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDel)
                    .addComponent(btnUpdate)
                    .addComponent(btnQuit))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtssActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
         ClientDao pl = new ClientImpl();
        int result = pl.DeleteClient(this.txtName.getText().trim());
        if(result > 0){
            JOptionPane.showMessageDialog(this, "删除成功");
            btnSearchActionPerformed(evt);
            btnQuitActionPerformed(evt);
        } else {
            JOptionPane.showMessageDialog(this, "删除失败");
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
         StringUtile su = new StringUtile();
        if(!su.validateNull(this.txtName.getText())){
            JOptionPane.showMessageDialog(this, "客户名称不允许为空！");
            return;
        }if(!su.validateDigit(this.txtTel.getText())){
            JOptionPane.showMessageDialog(this, "客户电话必须为数字！");
            return;
        }
        
        if(!su.validateNull(this.txtAddress.getText())){
            JOptionPane.showMessageDialog(this, "客户地址不允许为空！");
            return;
        }
        if(!su.validateDigit(this.txtPost.getText())){
            JOptionPane.showMessageDialog(this, "客户邮编必须为数字！");
            return;
        }
        
        //UUIDUtils uuid = new UUIDUtils();
        Client p = new Client();
        //p.setcId(uuid.getUUID());
        p.setcName(this.txtName.getText().trim());//trim()去除前后空格
        p.setcTele(this.txtTel.getText().trim());
        p.setcAddress(this.txtAddress.getText().trim());
        p.setPostcodes(this.txtPost.getText().trim());
       
        ClientDao pl = new ClientImpl();
        
        if(pl.IsExist(p.getcName())){
            if(pl.UpdateClient(p)>0){
                JOptionPane.showMessageDialog(this, "同名客户已存在，该客户资料已更新！");
                btnSearchActionPerformed(evt);
            } else{
                JOptionPane.showMessageDialog(this, "同名客户已存在，该客户资料更新失败！");
            }
            btnQuitActionPerformed(evt);
            return;           
        }
        int result = pl.AddClient(p);
        if(result > 0){
            JOptionPane.showMessageDialog(this, "添加成功");
            btnSearchActionPerformed(evt);
            btnQuitActionPerformed(evt);
        } else {
            JOptionPane.showMessageDialog(this, "添加失败");
            btnQuitActionPerformed(evt);
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         StringUtile su = new StringUtile();
        if(!su.validateNull(this.txtName.getText())){
            JOptionPane.showMessageDialog(this, "客户名称不允许为空！");
            return;
        }if(!su.validateDigit(this.txtTel.getText())){
            JOptionPane.showMessageDialog(this, "客户电话必须为数字！");
            return;
        }
        
        if(!su.validateNull(this.txtAddress.getText())){
            JOptionPane.showMessageDialog(this, "客户地址不允许为空！");
            return;
        }
        if(!su.validateDigit(this.txtPost.getText())){
            JOptionPane.showMessageDialog(this, "客户邮编必须为数字！");
            return;
        }
        Client p = new Client();
        //p.setcId(uuid.getUUID());
        p.setcName(this.txtName.getText().trim());//trim()去除前后空格
        p.setcTele(this.txtTel.getText().trim());
        p.setcAddress(this.txtAddress.getText().trim());
        p.setPostcodes(this.txtPost.getText().trim());
       
        ClientDao pl = new ClientImpl();
        
        int result = pl.UpdateClient(p);
        if(result > 0){
            JOptionPane.showMessageDialog(this, "更新成功");
            btnSearchActionPerformed(evt);
            btnQuitActionPerformed(evt);
        } else {
            JOptionPane.showMessageDialog(this, "更新失败");
            btnQuitActionPerformed(evt);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        ClientDao pl = new ClientImpl();
        String value = this.txtss.getText();
        List<Client> list = pl.QueryClient(value);
        
        if(!list.isEmpty()){
            this.btnUpdate.setEnabled(true);
            this.btnDel.setEnabled(true);
        }
        DefaultTableModel tm = (DefaultTableModel)tblClient.getModel();
        while (tm.getRowCount() > 0) {
            tm.removeRow(tm.getRowCount() - 1);//逐行清除表中内容
        }
        
        for(Client p:list){
            String [] str = {p.getcName(),p.getcTele(), p.getcAddress(),p.getPostcodes()};
            tm.addRow(str);
        }
        if(list.isEmpty()){
                JOptionPane.showMessageDialog(this, "没有该客户信息");
                return;
            }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
        this.txtName.setText("");
        this.txtTel.setText("");
        this.txtAddress.setText("");
        this.txtPost.setText("");
        this.btnAdd.setEnabled(true);
        this.btnUpdate.setEnabled(false);
        this.btnDel.setEnabled(false);
        this.txtName.setEditable(true);
    }//GEN-LAST:event_btnQuitActionPerformed

    private void tblClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel)tblClient.getModel();
        //获取当前行
        int row = this.tblClient.getSelectedRow();
        this.txtName.setText(tm.getValueAt(row, 0).toString());
        this.txtTel.setText(tm.getValueAt(row, 1).toString());
        this.txtAddress.setText(tm.getValueAt(row, 2).toString());
        this.txtPost.setText(tm.getValueAt(row, 3).toString());
        this.btnAdd.setEnabled(false);
        this.btnUpdate.setEnabled(true);
        this.btnDel.setEnabled(true);
        this.txtName.setEditable(false);
    }//GEN-LAST:event_tblClientMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tblAddress;
    private javax.swing.JTable tblClient;
    private javax.swing.JLabel tblName;
    private javax.swing.JLabel tblPost;
    private javax.swing.JLabel tblTel;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPost;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtss;
    // End of variables declaration//GEN-END:variables
}
