/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pss.view;

import com.pss.dao.ProductDao;
import com.pss.dao.ProductImpl;
import com.pss.dao.supplierImpl;
import com.pss.dao.supplierdao;
import com.pss.po.Buy;
import com.pss.po.Product;
import com.pss.util.LocationUtil;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class InventoryQuery extends javax.swing.JInternalFrame {

    /**
     * Creates new form InventoryQuery
     */
    public InventoryQuery() {
        initComponents();
        LocationUtil.setFullScreen(this);  //设置全屏显示
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        buttonGroup17 = new javax.swing.ButtonGroup();
        buttonGroup18 = new javax.swing.ButtonGroup();
        buttonGroup19 = new javax.swing.ButtonGroup();
        buttonGroup20 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        protable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        checkname = new javax.swing.JRadioButton();
        checktype = new javax.swing.JRadioButton();
        txtcheck = new javax.swing.JTextField();
        btncheck = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("库存查询");

        protable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "商品编号", "商品名称 ", "商品类型", "当前库存", "安全库存", "建议采购价", "最近采购日期", "建议销售价", "最近销售日期"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        protable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                protableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(protable);

        jLabel1.setText("查询条件：");

        buttonGroup1.add(checkname);
        checkname.setText("商品名称");
        checkname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checknameActionPerformed(evt);
            }
        });

        buttonGroup1.add(checktype);
        checktype.setText("商品类型");
        checktype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checktypeActionPerformed(evt);
            }
        });

        txtcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcheckActionPerformed(evt);
            }
        });

        btncheck.setText("查询");
        btncheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkname)
                .addGap(18, 18, 18)
                .addComponent(checktype)
                .addGap(148, 148, 148)
                .addComponent(txtcheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btncheck)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checktype)
                    .addComponent(checkname)
                    .addComponent(jLabel1)
                    .addComponent(txtcheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncheck))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void protableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_protableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_protableMouseClicked

    private void txtcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcheckActionPerformed

    private void btncheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckActionPerformed
        // TODO add your handling code here:
        if(checkname.isSelected()){
            String value = this.txtcheck.getText();
            ProductDao pl = new ProductImpl();
            List<Product> list = pl.QueryProductByName(value);
            DefaultTableModel tm = (DefaultTableModel)protable.getModel();
            while (tm.getRowCount() > 0) {
                tm.removeRow(tm.getRowCount() - 1);//逐行清除表中内容
            }    
             if(list.isEmpty()){
                     JOptionPane.showMessageDialog(this, "没有该商品库存信息！");
                     this.txtcheck.setText("");
                }
            for(Product p:list){

                String [] str = {String.valueOf(p.getpNo()),p.getpName(),p.getType(),String.valueOf(p.getNowStock()),String.valueOf(p.getSafeStock()), String.valueOf(p.getSuggestBuy()),String.valueOf(p.getLastBuyTime()),String.valueOf(p.getSuggestSell()),String.valueOf(p.getLastDeliverTime())};
                tm.addRow(str);
            }
        }
        else if(checktype.isSelected())
        {
            String value = this.txtcheck.getText();
            ProductDao pl = new ProductImpl();
            List<Product> list = pl.QueryProductByType(value);
            DefaultTableModel tm = (DefaultTableModel)protable.getModel();
            while (tm.getRowCount() > 0) {
                tm.removeRow(tm.getRowCount() - 1);//逐行清除表中内容
            }    
             if(list.isEmpty()){
                     JOptionPane.showMessageDialog(this, "没有该类型商品库存信息！");
                     this.txtcheck.setText("");
                }
            for(Product p:list){

                String [] str = {String.valueOf(p.getpNo()),p.getpName(),p.getType(),String.valueOf(p.getNowStock()),String.valueOf(p.getSafeStock()), String.valueOf(p.getSuggestBuy()),String.valueOf(p.getLastBuyTime()),String.valueOf(p.getSuggestSell()),String.valueOf(p.getLastDeliverTime())};
                tm.addRow(str);
            }
        }else{
             JOptionPane.showMessageDialog(this, "请选择查询条件！");
             this.txtcheck.setText("");
        }
       
        
        
    }//GEN-LAST:event_btncheckActionPerformed

    private void checknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checknameActionPerformed

    private void checktypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checktypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checktypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncheck;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup17;
    private javax.swing.ButtonGroup buttonGroup18;
    private javax.swing.ButtonGroup buttonGroup19;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup20;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JRadioButton checkname;
    private javax.swing.JRadioButton checktype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable protable;
    private javax.swing.JTextField txtcheck;
    // End of variables declaration//GEN-END:variables
}
