/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pss.view;

import com.pss.dao.BuyDao;
import com.pss.dao.BuyImpl;
import com.pss.dao.ProductDao;
import com.pss.dao.ProductImpl;
import com.pss.dao.supplierImpl;
import com.pss.dao.supplierdao;
import com.pss.po.Buy;
import com.pss.po.Product;
import com.pss.po.Supplier;
import com.pss.util.LocationUtil;
import com.pss.util.StringUtile;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class PurchaseReturn extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame6
     */
    public PurchaseReturn() {
        initComponents();
        LocationUtil.setFullScreen(this);  //设置全屏显示
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textFound = new javax.swing.JTextPane();
        tipRefund = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        dateStart = new com.pss.util.DateChooserJButton();
        dateEnd = new com.pss.util.DateChooserJButton();
        tipBNo = new javax.swing.JLabel();
        textBNo = new javax.swing.JTextField();
        tipPNo = new javax.swing.JLabel();
        textPNo = new javax.swing.JTextField();
        tipBCount = new javax.swing.JLabel();
        textBCount = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("采购退货");

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "采购编号", "商品编号", "商品名", "采购数量", "采购价格", "供应商编号", "供应商"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduct);

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnSearch.setText("查询");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(textFound);

        tipRefund.setText("退货数量：");

        jButton2.setText("采购退货");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        dateStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateStartActionPerformed(evt);
            }
        });

        tipBNo.setText("采购编号：");

        textBNo.setEditable(false);

        tipPNo.setText("商品编号：");

        textPNo.setEditable(false);

        tipBCount.setText("采购数量：");

        textBCount.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(dateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(dateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tipBCount)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textBCount, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tipBNo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textBNo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(73, 73, 73)
                                        .addComponent(tipPNo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textPNo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tipRefund)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(jButton2)))))
                        .addGap(0, 261, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(dateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipBNo)
                    .addComponent(textBNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipPNo)
                    .addComponent(textPNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipBCount)
                    .addComponent(textBCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(tipRefund, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addGap(231, 231, 231))
        );

        tipRefund.getAccessibleContext().setAccessibleName("labelReturnNumber");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked
     //商品表
        DefaultTableModel tm = (DefaultTableModel) tblProduct.getModel();
        //获取当前行
        int row = this.tblProduct.getSelectedRow();
        textBNo.setText(tm.getValueAt(row, 0).toString().trim());
        textPNo.setText(tm.getValueAt(row, 1).toString().trim());
        textBCount.setText(tm.getValueAt(row, 3).toString().trim());
    }//GEN-LAST:event_tblProductMouseClicked

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // 搜索
        BuyImpl buy=new BuyImpl();
        List<Buy> buyList=buy.QueryBuyByTimeAndName(this.dateStart.getDate(), this.dateEnd.getDate(), this.txtSearch.getText());
        
        DefaultTableModel tm = (DefaultTableModel) tblProduct.getModel();
        while (tm.getRowCount() > 0) {
            tm.removeRow(tm.getRowCount() - 1);//逐行清除表中内容
        }
        
        for(Buy b:buyList)
        {
            ProductDao pd=new ProductImpl();
            Product p=pd.QueryProductByPNo(b.getpNo()).get(0);
            supplierdao sd=new supplierImpl();
            Supplier s=sd.QuerySupplierBySId(b.getsId()).get(0);
            
            String []str={
                b.getBuyNo(),
                b.getpNo(),
                p.getpName(),
                String.format("%d",b.getBuyCount()),
                String.format("%f",b.getPrice()),
                String.format("%d",b.getsId()),
                s.getsName()};
            tm.addRow(str);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if (!StringUtile.validateNull(textFound.getText())) {
            JOptionPane.showMessageDialog(this, "退货数量不允许为空！");
            return;
        }
        if (!StringUtile.validateDigit(textFound.getText())) {
            JOptionPane.showMessageDialog(this, "退货数量必须为数字！");
            return;
        }
        int foundCount=Integer.parseInt(textFound.getText());
        DefaultTableModel tm = (DefaultTableModel) tblProduct.getModel();
        //获取当前行
        int row = this.tblProduct.getSelectedRow();
        int buyCount=Integer.parseInt(tm.getValueAt(row, 3).toString().trim());
        if(foundCount>buyCount)
        {
            JOptionPane.showMessageDialog(this, "退货数量多余购置数量！");
            return ;
        }
        ProductDao pd=new ProductImpl();
        Product p=pd.QueryProductByPNo(textPNo.getText()).get(0);
        int stock=p.getSafeStock();
        if(foundCount>stock)
        {
            JOptionPane.showMessageDialog(this, "退货数量多余库存数量！");   
            return;
        }
        else
        {
            pd.UpdateProductStockPlus(p.getpNo(), foundCount);
            JOptionPane.showMessageDialog(this, "退货成功！");  
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dateStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateStartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private com.pss.util.DateChooserJButton dateEnd;
    private com.pss.util.DateChooserJButton dateStart;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField textBCount;
    private javax.swing.JTextField textBNo;
    private javax.swing.JTextPane textFound;
    private javax.swing.JTextField textPNo;
    private javax.swing.JLabel tipBCount;
    private javax.swing.JLabel tipBNo;
    private javax.swing.JLabel tipPNo;
    private javax.swing.JLabel tipRefund;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
