/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pss.view;

import com.pss.dao.BuyDao;
import com.pss.dao.BuyImpl;
import com.pss.dao.ProductDao;
import com.pss.dao.ProductImpl;
import com.pss.dao.supplierImpl;
import com.pss.dao.supplierdao;
import com.pss.po.Buy;
import com.pss.po.Product;
import com.pss.po.Supplier;
import com.pss.util.LocationUtil;
import com.pss.util.StringUtile;
import com.pss.util.UUIDUtils;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class PurchasingIn extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame5
     */
    public PurchasingIn() {
        initComponents();
        LocationUtil.setFullScreen(this);  //设置全屏显示
        btnAdd.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("采购入库");

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "商品名称", "商品类型", "安全存量", "当前库存", "建议购买价"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduct);

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "供应商编号", "供应商姓名", "商品名称", "采购价格", "采购数量"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupplierMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSupplier);

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnSearch.setText("查询");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel2.setText("加入采购");

        btnAdd.setText("采购");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 173, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked
        //商品表
        DefaultTableModel tm = (DefaultTableModel) tblProduct.getModel();
        //获取当前行
        int row = this.tblProduct.getSelectedRow();
        String goods = tm.getValueAt(row, 0).toString().trim();
        supplierdao sDao = new supplierImpl();
        List<Supplier> list = sDao.QuerySupplierByGoods(goods);

        if (list != null) {//设置采购按钮是否禁用
            btnAdd.setEnabled(true);
        } else {
            btnAdd.setEnabled(false);
        }
        DefaultTableModel tms = (DefaultTableModel) tblSupplier.getModel();
        while (tms.getRowCount() > 0) {
            tms.removeRow(tm.getRowCount() - 1);//逐行清除表中内容
        }
        
        //最奇怪的bug
        for (Supplier s : list) {
            String[] str = {String.valueOf(s.getsId()), s.getsName(), s.getGoods(), String.valueOf(s.getPrice()), ""};
            tms.addRow(str);
        }

    }//GEN-LAST:event_tblProductMouseClicked

    private void tblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupplierMouseClicked
        //供应商表

    }//GEN-LAST:event_tblSupplierMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // 搜索
        String value = this.txtSearch.getText();
        ProductDao pDao = new ProductImpl();
        List<Product> list = pDao.QueryProductByValue(value);

        DefaultTableModel tm = (DefaultTableModel) tblProduct.getModel();
        while (tm.getRowCount() > 0) {
            tm.removeRow(tm.getRowCount() - 1);//逐行清除表中内容
        }
        // JTable tb = new JTable(tm);
        // DefaultTableCellRenderer bColor = new DefaultTableCellRenderer();   //该类可改变单元格的背景，字体等。
        // bColor.setBackground(Color.red);
        // int i = 0;
        for (Product p : list) {
            String[] str = {p.getpName(), p.getType(), String.valueOf(p.getSafeStock()), String.valueOf(p.getNowStock()), String.valueOf(p.getSuggestBuy())};
            tm.addRow(str);
//            if (p.getSafeStock() >= p.getNowStock()) {
//                //商品存量不足，该行标红色
//                tb.getCellEditor(i++, 1).getTableCellEditorComponent(tb, value, isSelected, ERROR, WIDTH).setBackground(Color.red);
//            }

        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // 采购
        
       // List<String[]> list = new ArrayList<>();
        DefaultTableModel tm = (DefaultTableModel) tblSupplier.getModel();        


        String buyNumber=tblSupplier.getValueAt(tblSupplier.getSelectedRow(),4).toString().trim();
        if (!StringUtile.validateNull(buyNumber)) {
            JOptionPane.showMessageDialog(this, "购买数量不允许为空！");
            return;
        }
        if (!StringUtile.validateDigit(tblSupplier.getValueAt(tblSupplier.getSelectedRow(),4).toString().trim())) {
            JOptionPane.showMessageDialog(this, "购买数量必须为数字！");
            return;
        }   
        JOptionPane.showMessageDialog(this, "购买数量："+buyNumber);
        Buy b = new Buy();
        b.setBuyNo(UUIDUtils.getUUID());//采购单号
        b.setsId(Integer.valueOf(tblSupplier.getValueAt(tblSupplier.getSelectedRow(),0).toString().trim()));//供应商编号
        ProductDao pDao = new ProductImpl();
        for (Product p : pDao.QueryProductByName(String.valueOf(tblSupplier.getValueAt(tblSupplier.getSelectedRow(),2).toString().trim()))) {
            b.setpNo(p.getpNo());//商品编号
        }
        b.setPrice(Double.valueOf(tblSupplier.getValueAt(tblSupplier.getSelectedRow(),3).toString().trim()));//商品价格
        b.setBuyCount(Integer.valueOf(tblSupplier.getValueAt(tblSupplier.getSelectedRow(),4).toString().trim()));//商品数量
        BuyDao bDao = new BuyImpl();
        if (bDao.AddBuy(b) > 0) {
            pDao.UpdateProductStock(b.getpNo(), b.getBuyCount());
            JOptionPane.showMessageDialog(this, "采购成功！");
            //btnSearchActionPerformed(evt);
        } else {
            JOptionPane.showMessageDialog(this, "采购失败！");
        }


    }//GEN-LAST:event_btnAddActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
