/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pss.view;

import com.pss.dao.IUser;
import com.pss.dao.UserIMPL;
import com.pss.po.User;
import com.pss.util.DBConnection;
import com.pss.util.LocationUtil;
import com.pss.util.StringUtile;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class StaffManagement extends javax.swing.JInternalFrame {
     IUser ipd = new UserIMPL();

    /**
     * Creates new form NewJInternalFrame3
     */
    public StaffManagement() {
        initComponents();
        LocationUtil.setFullScreen(this);  //设置全屏显示
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSeach = new javax.swing.JTextField();
        btnSeach = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        txtName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPosition = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        txtPhone = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnConcel = new javax.swing.JButton();
        txtAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSex = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPlace = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("员工管理");

        txtSeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeachActionPerformed(evt);
            }
        });

        btnSeach.setText("查询");
        btnSeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeachActionPerformed(evt);
            }
        });

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "员工编号", "员工姓名", "职位", "电话", "现住址", "性别", "籍贯", "邮箱"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblUser);

        jLabel8.setText("邮箱：");

        jLabel3.setText("职位：");

        btnAdd.setText("增加");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel4.setText("电话：");

        btnUpdate.setText("修改");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("删除");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel5.setText("现住址：");

        btnConcel.setText("取消");
        btnConcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcelActionPerformed(evt);
            }
        });

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        jLabel6.setText("性别：");

        jLabel1.setText("员工编号：");

        txtId.setEditable(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        jLabel7.setText("籍贯：");

        jLabel2.setText("员工姓名：");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(txtSeach, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(btnSeach))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtAddress))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName)
                            .addComponent(txtSex, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(btnConcel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSeach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeach))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnConcel))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeachActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_txtSeachActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String name = this.txtName.getText().trim();//.trim()去除前后空格 防止空格的输入
        String position = this.txtPosition.getText().trim();
        String phone = this.txtPhone.getText().trim();
        String address = this.txtAddress.getText().trim();
        String sex = this.txtSex.getText().trim();
        String place = this.txtPlace.getText().trim();
        String email = this.txtEmail.getText().trim();
        //判断输入的数据是否为空和价格是否为数字  公用工具类
//            if (sql.equals(0)){
        System.out.println("用户登陆权限：" + LoginFrame.user.getAuthority().equals("0"));
        System.out.println("用户xinxi：" + LoginFrame.user.getuName());
        if (LoginFrame.user.getAuthority().equals("0")) {
            if (StringUtile.validateNull(name) == false) {
                JOptionPane.showMessageDialog(this, "销售员名称不能为空");
                return;
            }
            if (StringUtile.validateNull(position) == false) {
                JOptionPane.showMessageDialog(this, "销售员职位不能为空");
                return;
            }
            if (StringUtile.validateNull(address) == false) {
                JOptionPane.showMessageDialog(this, "销售员现住址不能为空");
                return;
            }
            if (StringUtile.validateNull(position) == false) {
                JOptionPane.showMessageDialog(this, "销售员职位不能为空");
                return;
            }
            if (StringUtile.validateNull(sex) == false) {
                JOptionPane.showMessageDialog(this, "销售员性别不能为空");
                return;
            }
            if (StringUtile.validateNull(place) == false) {
                JOptionPane.showMessageDialog(this, "销售员籍贯不能为空");
                return;
            }
            if (StringUtile.validateNull(email) == false) {
                JOptionPane.showMessageDialog(this, "销售员邮箱不能为空");
                return;
            }
            if (StringUtile.validateDigit(phone) == false) {
                JOptionPane.showMessageDialog(this, "销售员手机号必须为数字");
                return;
            }

            com.pss.po.User p = new com.pss.po.User(name, position, phone, address, sex, place, email);
            if (ipd.isExit(p.getuTele(), p.getEmail())) {

                JOptionPane.showMessageDialog(this, "该电话或邮箱已存在，请重新输入！");
                btnSeachActionPerformed(evt);
                btnConcelActionPerformed(evt);
                return;

            } else {
                int result = ipd.addUser(p);
                if (result > 0) {
                    //在窗口提示添加成功
                    JOptionPane.showMessageDialog(this, "添加成功");
                    btnSeachActionPerformed(evt);
                    btnConcelActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(this, "添加失败");
                    btnConcelActionPerformed(evt);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "请用管理员身份登录");
            btnConcelActionPerformed(evt);
        }
           
 
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnConcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcelActionPerformed
        // TODO add your handling code here:
        this.txtId.setText("");
        this.txtName.setText("");
        this.txtPhone.setText("");
        this.txtPosition.setText("");
        this.txtAddress.setText("");
        this.txtSex.setText("");
        this.txtPlace.setText("");
        this.txtEmail.setText("");
        this.btnAdd.setEnabled(true);
        this.btnUpdate.setEnabled(false);
        this.btnDelete.setEnabled(false);
    }//GEN-LAST:event_btnConcelActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnSeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeachActionPerformed
        // TODO add your handling code here:
        String str = this.txtSeach.getText();
        List<com.pss.po.User> lp = ipd.getUser(str);
        DefaultTableModel dtm = (DefaultTableModel) this.tblUser.getModel();
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
        }
        for(com.pss.po.User p :lp){
            Vector v = new Vector();
            v.add(p.getuId());
            v.add(p.getuName());
            v.add(p.getPosition());
            v.add(p.getuTele());
            v.add(p.getuAddress());
            v.add(p.getSex());
            v.add(p.getNativePlace());
            v.add(p.getEmail());
            dtm.addRow(v);
        
        }
    }//GEN-LAST:event_btnSeachActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        String sid = this.txtId.getText();
        int id = Integer.parseInt(sid);
        String name = this.txtName.getText().trim();//.trim()去除前后空格 防止空格的输入
        String position = this.txtPosition.getText().trim();
        String phone = this.txtPhone.getText().trim();
        String address = this.txtAddress.getText().trim();
        String sex = this.txtSex.getText().trim();
        String place = this.txtPlace.getText().trim();
        String email = this.txtEmail.getText().trim(); 
        //判断输入的数据是否为空和价格是否为数字  公用工具类 
         if (LoginFrame.user.getAuthority().equals("0")) {
         if (StringUtile.validateNull(name) == false) {
                JOptionPane.showMessageDialog(this, "销售员名称不能为空");
                return;
            }
            if (StringUtile.validateNull(position) == false) {
                JOptionPane.showMessageDialog(this, "销售员职位不能为空");
                return;
            }
            if (StringUtile.validateNull(address) == false) {
                JOptionPane.showMessageDialog(this, "销售员现住址不能为空");
                return;
            }
            if (StringUtile.validateNull(position) == false) {
                JOptionPane.showMessageDialog(this, "销售员职位不能为空");
                return;
            }
            if (StringUtile.validateNull(sex) == false) {
                JOptionPane.showMessageDialog(this, "销售员性别不能为空");
                return;
            }
            if (StringUtile.validateNull(place) == false) {
                JOptionPane.showMessageDialog(this, "销售员籍贯不能为空");
                return;
            }
            if (StringUtile.validateNull(email) == false) {
                JOptionPane.showMessageDialog(this, "销售员邮箱不能为空");
                return;
            }
            if (StringUtile.validateDigit(phone) == false) {
                JOptionPane.showMessageDialog(this, "销售员手机号必须为数字");
                return;
            }
       com.pss.po.User p = new com.pss.po.User(id,name, position, phone, address, sex, place, email);
        int result = ipd.UpdateUser(p);
        if(result > 0){
            JOptionPane.showMessageDialog(this, "修改成功");
             btnConcelActionPerformed( evt);
            btnSeachActionPerformed( evt);
        }else{
            JOptionPane.showMessageDialog(this, "修改失败");
            btnConcelActionPerformed( evt);
        }
         }else {
            JOptionPane.showMessageDialog(this, "请用管理员身份登录");
            btnConcelActionPerformed(evt);
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserMouseClicked
        // TODO add your handling code here:
        int selectRow=this.tblUser.getSelectedRow();
        Integer idd=(Integer)this.tblUser.getValueAt(selectRow, 0);
        this.txtId.setText(idd.toString());
        this.txtName.setText((String)this.tblUser.getValueAt(selectRow, 1));
        this.txtPosition.setText((String)this.tblUser.getValueAt(selectRow, 2));
        this.txtPhone.setText((String)this.tblUser.getValueAt(selectRow, 3));
        this.txtAddress.setText((String)this.tblUser.getValueAt(selectRow, 4));
        this.txtSex.setText((String)this.tblUser.getValueAt(selectRow, 5));
        this.txtPlace.setText((String)this.tblUser.getValueAt(selectRow, 6));
        this.txtEmail.setText((String)this.tblUser.getValueAt(selectRow, 7));
        this.btnAdd.setEnabled(false);
        this.btnUpdate.setEnabled(true);
        this.btnDelete.setEnabled(true);
    }//GEN-LAST:event_tblUserMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String sid=this.txtId.getText();
        int id=Integer.parseInt(sid);
       
        if (LoginFrame.user.getAuthority().equals("0")) {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
           int result = ipd.deleteUser(id);
           if(result==998 ){
            JOptionPane.showMessageDialog(this, "不可删除：因为该员工还存在负责的供应商！");
            btnConcelActionPerformed( evt);
            btnSeachActionPerformed( evt);         
        }else if(result > 0 ){
            JOptionPane.showMessageDialog(this, "删除成功");
            btnConcelActionPerformed( evt);
            btnSeachActionPerformed( evt);         
        }else{
            JOptionPane.showMessageDialog(this, "删除失败");
            btnConcelActionPerformed( evt);
        }
         }else {
            JOptionPane.showMessageDialog(this, "请用管理员身份登录");
            btnConcelActionPerformed(evt);
        }
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnConcel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSeach;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPlace;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtSeach;
    private javax.swing.JTextField txtSex;
    // End of variables declaration//GEN-END:variables
}
