/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pss.view;

import com.pss.dao.IUser;
import com.pss.dao.ProductDao;
import com.pss.dao.ProductImpl;
import com.pss.dao.UserIMPL;
import com.pss.dao.supplierImpl;
import com.pss.dao.supplierdao;
import com.pss.po.Buy;
import com.pss.po.Product;
import com.pss.po.Supplier;
import com.pss.po.User;
import com.pss.util.FrameUtil2;
import com.pss.util.LocationUtil;
import com.pss.util.StringUtile;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class SupplierInformation extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame1
     */
    public SupplierInformation() {
        initComponents();
        LocationUtil.setFullScreen(this);  //设置全屏显示
        this.btnUpdate.setEnabled(false);
        this.btnDelete.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        suppliertable = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtsid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtsname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtuid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtgoods = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtstele = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtplantaddress = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtfax = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtfirmaddress = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("供应商资料");

        suppliertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "供应商编号", "供应商名称", "负责人", "商品", "商品价格", "电话", "传真", "公司地址", "工厂地址"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        suppliertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suppliertableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(suppliertable);

        btnAdd.setText("新增");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("更新");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("删除");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSearch.setText("查询");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel1.setText("供应商编号：");

        txtsid.setEditable(false);
        txtsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsidActionPerformed(evt);
            }
        });

        jLabel2.setText("供应商名称：");

        txtsname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsnameActionPerformed(evt);
            }
        });

        jLabel3.setText("负责人：");

        txtuid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuidActionPerformed(evt);
            }
        });

        jLabel4.setText("商品：");

        txtgoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgoodsActionPerformed(evt);
            }
        });

        jLabel5.setText("商品价格：");

        jLabel6.setText("电话：");

        jLabel7.setText("工厂地址：");

        txtplantaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplantaddressActionPerformed(evt);
            }
        });

        btnCancel.setText("取消");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel8.setText("传真：");

        jLabel9.setText("公司地址：");

        txtfirmaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfirmaddressActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnAdd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnUpdate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnDelete, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnSearch, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtsid, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtsname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtuid, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtgoods, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtprice, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtstele, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtplantaddress, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnCancel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtfax, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtfirmaddress, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsid, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8))
                                .addGap(40, 40, 40)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtfax)
                                    .addComponent(txtgoods, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))))
                        .addGap(0, 44, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdate)
                        .addGap(60, 60, 60)))
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtprice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(txtsname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfirmaddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(22, 22, 22)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtstele, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(txtuid)))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtplantaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearch)
                        .addGap(63, 63, 63)
                        .addComponent(btnCancel)
                        .addGap(150, 150, 150))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtsid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtsname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtuid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtgoods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtstele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtfax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtfirmaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtplantaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSearch)
                        .addComponent(btnCancel)
                        .addComponent(btnDelete)
                        .addComponent(btnUpdate)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        StringUtile su = new StringUtile();
        IUser user=new UserIMPL();
        if(!su.validateNull(this.txtsname.getText())){
            JOptionPane.showMessageDialog(this, "供应商名称不允许为空！");
            return;
        }if(!su.validateDigit(this.txtuid.getText())){
            JOptionPane.showMessageDialog(this, "请填入正确的负责人编号！");
            return;
        }
         if(!user.IsIDExist(Integer.parseInt(this.txtuid.getText()))){
                JOptionPane.showMessageDialog(this, "负责人编号不存在！");
                return;
            }
        if(!su.validateNull(this.txtgoods.getText())){
            JOptionPane.showMessageDialog(this, "商品名称不允许为空！");
            return;
        }
        if(!su.validateDigit(this.txtprice.getText())){
            JOptionPane.showMessageDialog(this, "商品价格必须为数字！");
            return;
        }
        if(!su.validateNull(this.txtstele.getText())){
            JOptionPane.showMessageDialog(this, "电话不能为空！");
            return;
        }
        if(!su.validateNull(this.txtfax.getText())){
            JOptionPane.showMessageDialog(this, "传真不能为空！");
            return;
        }
        if(!su.validateNull(this.txtfirmaddress.getText())){
            JOptionPane.showMessageDialog(this, "公司地址不能为空！");
            return;
        }
        if(!su.validateNull(this.txtplantaddress.getText())){
            JOptionPane.showMessageDialog(this, "工厂地址不能为空！");
            return;
        }
        Supplier p = new Supplier();
        p.setsName(this.txtsname.getText().trim());//trim()去除前后空格
        p.setuId(Integer.valueOf(this.txtuid.getText().trim()));
        p.setGoods(this.txtgoods.getText().trim());
        p.setPrice(Double.valueOf(this.txtprice.getText().trim()));
        p.setsTele(this.txtstele.getText().trim());
        p.setFax(this.txtfax.getText().trim());
        p.setFirmAddress(this.txtfirmaddress.getText().trim());
        p.setPlantAddress(this.txtplantaddress.getText().trim());
        supplierdao pl = new supplierImpl();
        
        if(pl.IsExist(p.getsName())){
            if(pl.UpdateSupplier(p)>0){
                JOptionPane.showMessageDialog(this, "同名同类商品已存在，该商品库存已更新！");
                btnSearchActionPerformed(evt);
            } else{
                JOptionPane.showMessageDialog(this, "同名同类商品已存在，该商品库存更新失败！");
            }
            btnCancelActionPerformed(evt);
            return;           
        }
        int result = pl.AddSupplier(p);
        if(result > 0){
            JOptionPane.showMessageDialog(this, "添加成功");
            btnCancelActionPerformed(evt);
            btnSearchActionPerformed(evt);
            
        } else {
            JOptionPane.showMessageDialog(this, "添加失败");
            btnCancelActionPerformed(evt);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        supplierdao pl = new supplierImpl();
        int result = pl.DeleteSupplierByName(this.txtsname.getText().trim());
        if(result > 0){
            JOptionPane.showMessageDialog(this, "删除成功");
            btnCancelActionPerformed(evt);
            btnSearchActionPerformed(evt);
           
        } else {
            JOptionPane.showMessageDialog(this, "删除失败");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtgoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgoodsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgoodsActionPerformed

    private void txtsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsidActionPerformed

    private void txtplantaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplantaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtplantaddressActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        StringUtile su = new StringUtile();
        if(!su.validateNull(this.txtsname.getText())){
            supplierdao pl = new supplierImpl();
            List<Supplier> list = pl.QuerySupplier();  
            if(!list.isEmpty()){
                this.btnUpdate.setEnabled(true);
                this.btnDelete.setEnabled(true);
            }
            DefaultTableModel tm = (DefaultTableModel)suppliertable.getModel();
            while (tm.getRowCount() > 0) {
                tm.removeRow(tm.getRowCount() - 1);//逐行清除表中内容
            }

            for(Supplier p:list){
                String [] str = {String.valueOf(p.getsId()), p.getsName(),String.valueOf(p.getuId()),p.getGoods(),Double.toString(p.getPrice()),p.getsTele(),p.getFax(),p.getFirmAddress(),p.getPlantAddress()};
                tm.addRow(str);
            }
        }else{
            supplierdao pl = new supplierImpl();
            String value=this.txtsname.getText();
            List<Supplier> list = pl.QuerySupplierByName(value);  
            if(!list.isEmpty()){
                this.btnUpdate.setEnabled(true);
                this.btnDelete.setEnabled(true);               
            }
            DefaultTableModel tm = (DefaultTableModel)suppliertable.getModel();
            while (tm.getRowCount() > 0) {
                tm.removeRow(tm.getRowCount() - 1);//逐行清除表中内容
            }
            for(Supplier p:list){
                String [] str = {String.valueOf(p.getsId()), p.getsName(),String.valueOf(p.getuId()),p.getGoods(),Double.toString(p.getPrice()),p.getsTele(),p.getFax(),p.getFirmAddress(),p.getPlantAddress()};
                tm.addRow(str);
             }
            if(list.isEmpty()){
                JOptionPane.showMessageDialog(this, "没有该供应商信息");
                this.txtsname.setText("");
            }
        } 
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtfirmaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirmaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirmaddressActionPerformed
                                 
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.txtsid.setText("");
        this.txtsname.setText("");
        this.txtuid.setText("");
        this.txtgoods.setText("");
        this.txtprice.setText("");
        this.txtstele.setText("");
        this.txtfax.setText("");
        this.txtfirmaddress.setText("");
        this.txtplantaddress.setText("");
        this.btnAdd.setEnabled(true);
        this.btnUpdate.setEnabled(false);
        this.btnDelete.setEnabled(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        StringUtile su = new StringUtile();
        IUser user=new UserIMPL();
        if(!su.validateNull(this.txtsname.getText())){
            JOptionPane.showMessageDialog(this, "供应商名称不允许为空！");
            return;
        }
        if(!su.validateDigit(this.txtuid.getText())){
            JOptionPane.showMessageDialog(this, "请填入正确的负责人编号！");      
            return;
        }
        if(!user.IsIDExist(Integer.parseInt(this.txtuid.getText()))){
                JOptionPane.showMessageDialog(this, "负责人编号不存在！");
                return;
            }
        
        if(!su.validateNull(this.txtgoods.getText())){
            JOptionPane.showMessageDialog(this, "商品名称不允许为空！");
            return;
        }
        if(!su.validateDigit(this.txtprice.getText())){
            JOptionPane.showMessageDialog(this, "商品价格必须为数字！");
            return;
        }
        if(!su.validateNull(this.txtstele.getText())){
            JOptionPane.showMessageDialog(this, "电话不能为空！");
            return;
        }
        if(!su.validateNull(this.txtfax.getText())){
            JOptionPane.showMessageDialog(this, "传真不能为空！");
            return;
        }
        if(!su.validateNull(this.txtfirmaddress.getText())){
            JOptionPane.showMessageDialog(this, "公司地址不能为空！");
            return;
        }
        if(!su.validateNull(this.txtplantaddress.getText())){
            JOptionPane.showMessageDialog(this, "工厂地址不能为空！");
            return;
        }
        Supplier p = new Supplier();
        p.setsName(this.txtsname.getText().trim());//trim()去除前后空格
        p.setuId(Integer.valueOf(this.txtuid.getText().trim()));
        p.setGoods(this.txtgoods.getText().trim());
        p.setPrice(Double.valueOf(this.txtprice.getText().trim()));
        p.setsTele(this.txtstele.getText().trim());
        p.setFax(this.txtfax.getText().trim());
        p.setFirmAddress(this.txtfirmaddress.getText().trim());
        p.setPlantAddress(this.txtplantaddress.getText().trim());
        supplierdao pl = new supplierImpl();
        int result = pl.UpdateSupplier(p);
        if(result > 0){
            JOptionPane.showMessageDialog(this, "更新成功");
            btnSearchActionPerformed(evt);
            btnCancelActionPerformed(evt);
        } else {
            JOptionPane.showMessageDialog(this, "更新失败,不能修改商品名称！");
            btnCancelActionPerformed(evt);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed
    
    private void suppliertableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppliertableMouseClicked
        // TODO add your handling code here:
          
      DefaultTableModel tm = (DefaultTableModel)suppliertable.getModel();
        //获取当前行
        int row = this.suppliertable.getSelectedRow();
        this.txtsid.setText(tm.getValueAt(row, 0).toString());
        this.txtsname.setText(tm.getValueAt(row, 1).toString());
        this.txtuid.setText(tm.getValueAt(row, 2).toString());
        this.txtgoods.setText(tm.getValueAt(row, 3).toString());
        this.txtprice.setText(tm.getValueAt(row, 4).toString());
        this.txtstele.setText(tm.getValueAt(row, 5).toString());
        this.txtfax.setText(tm.getValueAt(row, 6).toString());
        this.txtfirmaddress.setText(tm.getValueAt(row, 7).toString());
        this.txtplantaddress.setText(tm.getValueAt(row, 8).toString());
        this.btnAdd.setEnabled(false);
        this.btnUpdate.setEnabled(true);
        this.btnDelete.setEnabled(true);
        this.txtsid.setEditable(false);

    }//GEN-LAST:event_suppliertableMouseClicked

    private void txtuidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuidActionPerformed

    private void txtsnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsnameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable suppliertable;
    private javax.swing.JTextField txtfax;
    private javax.swing.JTextField txtfirmaddress;
    private javax.swing.JTextField txtgoods;
    private javax.swing.JTextField txtplantaddress;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtsid;
    private javax.swing.JTextField txtsname;
    private javax.swing.JTextField txtstele;
    private javax.swing.JTextField txtuid;
    // End of variables declaration//GEN-END:variables
}
